package com.passersbyte.naturally.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.passersbyte.naturally.model.Product;
import com.passersbyte.naturally.repository.ProductRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/app/products") // This means URL's start with /welcome (after Application path)
public class ProductController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private ProductRepository productRepository;
	
	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name
	 , @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
	
		Product n = new Product();
		n.setName(name);
		n.setValue(0);
		productRepository.save(n);
		return "Saved";
		}
		
		@GetMapping(path="/all")
		public @ResponseBody Iterable<Product> getAllProducts() {
		// This returns a JSON or XML with the users
		return productRepository.findAll();
		}
		
		@GetMapping("/topValue")
		public String greetings(Model model) {
			Pageable sortedByPriceDescNameAsc = 
					  PageRequest.of(0, 5, Sort.by("total").descending().and(Sort.by("name")));
			model.addAttribute("products", sortedByPriceDescNameAsc);
			return "topValue";
		}


}
